### PR TITLE
Upgrade django dependency to >=1.7

### PR DESCRIPTION
**Pull request by powersurge360**
Hey!

I made changes to get all the unit tests to pass with and without nose on django 1.7 & 1.8 on python 2.7 & python 3.4.

I also made a few minor changes to the tox file and the README, but I didn't touch the versioning or the docs. If you're fine with me updating those as well, I don't mind just let me know.

Let me know if anything is unsatisfactory.

### CODE REVIEW

**Comment by jwhitlock** [comment]
Thank you for the PR.  It will be a few weeks until I have a chance to look at it in detail.  My inclination is to make all supported Django versions work, but maybe we say v0.4 for 1.6 and earlier, and v0.5 for 1.7 and 1.8.

TravisCI isn't happy, with an error of "duplicate environment testenv:py27-django17-postgis":

https://travis-ci.org/tulsawebdevs/django-multi-gtfs/jobs/66629163

You can probably reproduce by running `tox`, or `make testall`.

**Comment by powersurge360** [comment]
Fixed the tox so it should work with the featureset as is. Going to do another branch to undo my tox changes and see if I can't get south migrations & in-built django migrations working together.

**Comment by powersurge360** [comment]
Finally had some time to get this working! Should now support django >1.5 with south migrations. I hadn't added it to the documentation, but to use south migrations, a SOUTH_MIGRATIONS_MODULE dictionary will need to be added in the settings per the south docs.

Let me know if you need me to touch up anything else :>

**Comment by jwhitlock** [comment]
Thanks! Are you able to use your branch in your project, or are you blocked on me merging?  It's best for me to do this first week of July, after finishing some June client work.

**Comment by powersurge360** [comment]
Yea, no rush, I'll just pull in my branch in the mean time.

**Comment by powersurge360** [comment]
Anything I can do to help this along?

**Comment by jwhitlock** [comment]
The June work took through July and August... I hope to get to this in the next few days.

**Comment by jwhitlock** [comment]
The code looks good.  There's some additional stuff I need to do before releasing a new version, but I can do that in master.

**Pull request merged**
